### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mclouvem** [tomatau/breko-hub#10]
Hi @tomatau!

I've update Koa to 1.1.2 and Reac-router to 2.0.0-rc5. Is there some reason why you didn't do it yet? 

If you agree, I'll submit a PR.

**Comment by tomatau** [comment]
Hi @mclouvem I'm hoping to move to koa-2.0 when it is more stable.

Also, same applies for RR-2.0-rc. I'm focusing on other parts of breko hub first (examples, more tests, etc...) and waiting for RR 2.0 to be released instead of an RC. We already have the desired functionality by creating a shared isomorphic history singleton.

**Comment by mclouvem** [comment]
I see and I agree with you. Can I help you with something else on those other parts? How can I contact you?
