### ISSUE TITLE
Overall questions/suggestions

### ISSUE THREAD

**Issue by nasushkov** [tomatau/breko-hub#34]
Hi, here are some questions/suggestions that I have on my mind after playing with this boilerplate for several days:

* Your koa server setup is spread across several files (partly in _app.js_, partly in _start.js_). So at the first time it's hard to grasp, what is happening here. Maybe it would be better to move koa app setup code to _app.js_ file and leave at _start.js_ only isomorphic tools configuration
* I'd suggest [react-helmet](https://github.com/nfl/react-helmet) as a more convenient way to manage page head 
* It also would be nice to add [react-intl](https://github.com/yahoo/react-intl) support for internationalization
* You have a socket.io support included in this boilerplate. There is no need for socket.io in my case. Is it necessary for any infrastructure to work properly (I mean hot-reload first of all)?

Thanks and keep up the good work.

**Comment by tomatau** [comment]
Hey @nasushkov thanks for this! Let me go through each of these.

- I'd suggest react-helmet as a more convenient way to manage page head
  - This looks very interesting! Want to make a PR? I'm not sure what the benefits are over react-document-meta?

- It also would be nice to add react-intl support for internationalization
  - In my experience with INTL support, implementations can be forced based on business requirements and so it would be hard to find a simple solution that meets everyone's requirements. I'll certainly have a play with this though! It could definitely help for big apps if done well!

- You have a socket.io support included in this boilerplate. There is no need for socket.io in my case.  Is it necessary for any infrastructure to work properly (I mean hot-reload first of all)?
  - Nope! You can remove it completely, all the hot reloading logic is handled within the hotReload file. The only infrastructure requirements are some dependency injection happening in the server.

- Your koa server setup is spread across several files (partly in app.js, partly in start.js). So at the first time it's hard to grasp, what is happening here. Maybe it would be better to move koa app setup code to app.js file and leave at start.js only isomorphic tools configuration
  - This is very much on purpose!
  - The scripts/start.js command hosts the root of hot reloading logic because it needs to sit outside of hotreloads to keep a single app instance.
  - Src/server/index.js hosts the app initialisation... this is so it can be tested! The tests plug in test routes to make sure this app middleware is configured correctly (error handling, compression, session)
  - Src/server/index.js is used to test in conjunction with Src/server/router.js... this is also for hot reloading of routes.. the router provides a function that assets can be injected into as well as allowing the makeRoutes function to be stubbed and hot reloaded.   I've wrote a blog article about the hot reloading here: https://tomatao-blog.herokuapp.com/ "Server and CSS Hot Updates"

**Comment by nasushkov** [comment]
Thanks,  Thomas, Your blog post clarifies a lot. React-helmet plays as a react-component so you can change page data on the client. For example, I use it for locale switching.

**Comment by tomatau** [comment]
Glad to hear it helped!

we're already using react-document-meta which does the same!
