### ISSUE TITLE
KoaJS compose 2.5.0 is breaking breko-hub

### ISSUE THREAD

**Issue by ykt** [tomatau/breko-hub#42]
Hi,

We have been using your boilerplate for our production app, just wanna let you current state `breko-hub` is broken due to `koa-compose@2.5.0` is used by `koa`.

You might refer this [issue](https://github.com/koajs/compose/issues/67)  for the detail, so the workaround for this boilerplate is explicitly used older version `koa-compose@2.4.0` in package.json.

Hope it might helps.

**Comment by tomatau** [comment]
Hey that's super cool you're using this boilerplate :)

So I can see koa@^1.2.4 is depending on `"koa-compose": "^2.3.0"` and so any new installs will break due to getting the new minor you're talking about. I'm a little reluctant to explicitly depend on a version of koa-compose that isn't actually used directly by this boilerplate. It could easily end up being an artefact when koa@1.x or koa-compose fix the issue and I don't quite have the time to keep a track of this issue between koa and koa compose!

I'm not entirely sure on the best action to take here as it sounds like a koa issue more than anything! Can you think of any other ways to avoid this problem? I wouldn't really want to lock down to koa@1.2.3 or something either!

It looks like they've got a branch ready for `koa-compose@v2.5.1` which should fix the problem soon and we won't need to change! It was just a day of unfortunate pain for you!

**Comment by ykt** [comment]
Yea, they have fixed the problem in this [commit](https://github.com/koajs/compose/commit/91b7d49cb8bb60c926bb712e221b2370c6452c80).
Thanks :)
